### ISSUE TITLE
d.ts declare module

### ISSUE THREAD

**Issue by tooooo1** [goorm-dev/gds-goormthon#1]
gds-goormthon version 0.0.5에 d.ts 몇 개가 정의되어 있지 않아요.

정의가 빠진 컴포넌트는 다음과 같습니다.
**GoormLoader, Status, TopBanner**

0.0.6 버전에 추가 부탁드려요!!

**Comment by ZeroChoi2781** [comment]
안녕하세요 @tooooo1 님!

해당 사항 추가해서 [v0.0.6](https://github.com/goorm-dev/gds-goormthon/pkgs/npm/gds-goormthon/38435434) 릴리즈했습니다.

감사합니다 : )
